version: 2
updates:
  # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Keep PRs manageable by limiting the number of open PRs
    open-pull-requests-limit: 5

  # Enable updates for Terraform
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    # Keep PRs manageable by limiting the number of open PRs
    open-pull-requests-limit: 5
