name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths: &trigger_paths
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths: *trigger_paths

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v5

      - name: Set up mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3

      - name: Set up lefthook
        run: lefthook install
